cds-snc/cds-aws-lz

- README.md
- terragrunt/main/organizations.tf
- Remove the production OU as we need to add it through Control Tower
- Update the README to document manual work 😭
> feat: remove ou and update README

- .github/workflows/tf-apply.yml
- .github/workflows/tf-plan.yml
- terragrunt/audit/main/.terraform.lock.hcl
- terragrunt/audit/main/main.tf
- terragrunt/audit/main/terragrunt.hcl
- terragrunt/audit/terragrunt.hcl
This work has already been applied locally as that is required at the
moment to bootstrap this process.
Also adds workflows to apply these changes.
> feat: add OIDC for audit account

- terragrunt/log_archive/main/guardduty.tf
Accepting invites will happen in a subsequent PR
> feat: invite all existing accounts to guardduty

- terragrunt/org_account/modules/assume_role/main.tf
> fix: use proper arn

- .github/workflows/tf-apply.yml
- .github/workflows/tf-plan.yml
- terragrunt/org_account/main/input.tf
- terragrunt/org_account/main/test.tf
Apply failed because we were running everything as the plan role
> fix: parameterize the assume role so we can apply

- terragrunt/org_account/main/guardduty.tf
> fix: Use the correct provider for us_west_2

- terragrunt/org_account/main/guardduty.tf
> fix: allow the other regions to manage the keys

- .github/workflows/tf-apply.yml
- .github/workflows/tf-plan.yml
we had LZ_* instead of LA_* and so the secrets weren't making it in.
> fix: change github secret keys

- terragrunt/org_account/main/sentinel_forwarders.tf
> fix: bucket name

- terragrunt/org_account/main/sentinel_forwarders.tf
> fix: bucket name attaempt 2

- terragrunt/org_account/main/securityhub.tf
Aggregate all findings into CA-CENTRAL-1
**Please Note: the log_archive security hub account resource was imported locally**
> feat: enable security hub region aggregation

- bin/invoke_customizations_all.sh
- bin/invoke_customizations_all_and_prod.sh
- bin/invoke_customizations_testbed.sh
Add some cli scripts that I use for invoking pipelines.
> feat: add some tools for invoke aft pipelines

- terragrunt/org_account/main/cloudtrail.tf
Replicate the org level cloudtrail logs to the bucket used by CCCS in
the Cloud Based Sensor Account
> feat: replicate Org Level CT to CBS bucket

- terragrunt/org_account/main/cloudtrail.tf
> fix: missing required field on Replication Configuration

- terragrunt/org_account/main/cloudtrail.tf
This should be the last item required for this work.
> fix: add delete_marker_replication

- bin/migrate/remove_aft_created_resources.sh
> fix: change from Scanfiles prod account ID to curr

- bin/migrate/get_lambda_resource_policies.sh
Get all the lambdas with policies that reference PrincipalOrgID
This is needed to help with Migration
> feat: get all lambdas with policies that ref orgId

- bin/migrate/create_awsctexec_role.sh
The role name was wrong causing lots of issues.
> fix: role name

- bin/one-offs/add_admin_policy.sh
Fixes: https://github.com/cds-snc/site-reliability-engineering/issues/572
> feat: Add one off fix for AdminAccess policy

- terragrunt/org_account/main/sentinel_forwarders.tf
> fix: location of cloudtrail logs

- terragrunt/org_account/spend_notifier/eventbridge.tf
> fix: use name instead of arn for target

- terragrunt/org_account/spend_notifier/lambdas/spend_notifier/spend_notifier.js
Instead of one section with multiple fields we are using multiple fields
per section.
Listen I know it's not pretty but it works and that's all I care about
for now.
> fix: block formatting for slack

- bin/create_ops_users.sh
Added a quick check to validate that the user is logged in lpass before applying the script.
> feat: Add lpass status evaluation

- .github/workflows/tf-apply.yml
- .github/workflows/tf-plan.yml
- terragrunt/aft/notifications/aft-notifications.tf
- terragrunt/aft/notifications/input.tf
- terragrunt/aft/notifications/terragrunt.hcl
> feat: add a notifier for AFT alerts.

- bin/create_ops_users.sh
> fix: update CT folder path

- terragrunt/org_account/main/main.tf
Import all existing OUs so they are proprly tracked in terraform.
Add a Test OU in support of
https://github.com/cds-snc/site-reliability-engineering/issues/654
> feat: import OUs and add Test OU.

- terragrunt/log_archive/legacy_archives/main.tf
Update S3 bucket names to match source buckets
> fix: name S3 buckets

- terragrunt/org_account/sre_bot/iam.tf
Updates the sre_bot IAM role to read cost and usage repo for accounts
> Update sre-bot iam.tf

- terragrunt/log_archive/legacy_archives/main.tf
Adding default KMS key to module
> fix: add default KMS key to module

- terragrunt/audit/sre_bot/iam.tf
This PR further scopes down the SRE Bot config role
> feat: scope config role

- terragrunt/org_account/main/locals.tf
- terragrunt/org_account/main/oidc_role.tf
This PR adds a new OIDC role to read cloud expenses
> feat: Add OIDC role to read Cloud Spend

- bin/invoke_customizations_ou.sh
Adding a basic script to invoke lambda for an OU provided as an argument
> feat: add base script to run invoke by OU as param

- terragrunt/org_account/main/scp.tf
This PR fixes the missing resource in the SCP.
> fix: add missing resource

- terragrunt/org_account/main/scp.tf
Fix removes one of the rules that does not apply
> fix: remove not_resources policy

- terragrunt/org_account/aft/.terraform.lock.hcl
- terragrunt/org_account/main/modules/global_controls/guardrails.tf
The for_each worked fine for new resources but we were unable to import
them.
I locally imported all the resources and moved the Testbed_SRC
There should be no changes in this PR.
Also updates the AFT lock file
> refactor: change guardrails so they work

- .github/workflows/tf-plan.yml
- terragrunt/aft/main/assume_roles.tf
- terragrunt/audit/main/assume_roles.tf
- terragrunt/log_archive/main/assume_roles.tf
- terragrunt/org_account/main/iam.tf
- terragrunt/org_account/main/locals.tf
- terragrunt/org_account/main/oidc_role.tf
- feat: update AFT assume role to use cds-aws-lz-plan
- feat: update audit roles
- feat: update log_archive role
- feat: remove old roles and associate new ones
Just because these have to be done in a certain order the changes were done locally so there should be little to no changes.
Closes #150  
Closes #151
> feat: update OIDC Roles to use new

- terragrunt/aft/notifications/.terraform.lock.hcl
- terragrunt/aft/notifications/aft-notifications.tf
Finally subscribing so these actually work
> feat: add subscriptions for notifications

- terragrunt/org_account/aft/main.tf
https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.7.0
https://github.com/aws-ia/terraform-aws-control_tower_account_factory/compare/1.6.2...1.7.0
https://github.com/hashicorp/terraform/releases/tag/v1.3.6
https://github.com/hashicorp/terraform/compare/v1.1.7...v1.3.6
> feat: upgrade AFT and TF Version for AFT

- terragrunt/org_account/spend_notifier/lambdas/spend_notifier/spend_notifier.js
Proposing to change first block to be header instead of section.
> fix: use header instead of section for header

- terragrunt/org_account/roles/cartography.tf
Apply is failing because of an invalid principle with this role, this role isn't needed till https://github.com/cds-snc/site-reliability-engineering/issues/663 is being actively worked on
> feat: temporarily disable cartography role

- terragrunt/org_account/aft/main.tf
Release notes: https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.9.1
> feat: upgrade AFT to 1.9.1

- terragrunt/org_account/spend_notifier/lambdas/spend_notifier/spend_notifier.js
Changing constructing of dates, since clearly the way I was doing it will not work for first few days of the month.... I don't know what I was thinking...
> Properly constructing dates

- terragrunt/org_account/spend_notifier/lambdas/spend_notifier/spend_notifier.js
Fixed up a bug with the dates and with the aws cost explorer api (basically read more documentation on it, and the end dates are exclusive whereas previously I understood them as inclusive).
> Bug fixes with dates and Aws cost explorer api

- terragrunt/org_account/spend_notifier/lambdas/spend_notifier/spend_notifier.js
For scratch accounts, since we are going back 2 days and if you don't account for that, there are errors since the start time is greater than the end time for the cost parameters. This PR fixes this issue.
> Adding a fix for the first 2 days of the month for scratch accounts calculation errors

- terragrunt/org_account/organization/guardrails.tf
Reapply the guardrails to the new Sandbox OU
> fix: apply Sandbox OU Guardrails

- terragrunt/org_account/roles/OIDC.tf
Final PR to destroy/create Sandbox OU: updating the OIDC role arn for Sandbox OU
> fix: update OIDC role arn

- .devcontainer/devcontainer.json
- .github/workflows/tf-apply.yml
- .github/workflows/tf-plan-aft.yml
- .github/workflows/tf-plan-org.yml
- .github/workflows/tf-plan.yml
- terragrunt/org_account/aft/main.tf
Upgrading terraform, terragrunt and conftest versions.
> Upgrading terraform, terragrunt and conftest versions

- catalog-info.yaml
Adding the system entity linking the 5 aws repos related to AFT
> feat: add the cds lz system to link components

- terragrunt/org_account/organization/organizations.tf
Adding the universal guardrails to the Test OU
> feat: enable universal guardrails on Test OU

- terragrunt/org_account/organization/organizations.tf
Attach the universal guardrails to the SRE tools OU
> fix: attach univ guardrails to SRE OU

- terragrunt/org_account/organization/organizations.tf
Attaching the universal guardrails to the Staging OU
> fix: attach universal guardrails to Staging OU

- terragrunt/org_account/organization/organizations.tf
apply the universal guardrails on prod OU
> feat: enable universal guardrails

- terragrunt/org_account/iam_identity_center/platform_cds_website_assignments.tf
- terragrunt/org_account/iam_identity_center/platform_notify_assignments.tf
Apply the permission assignment to the proper account
> fix: apply assignment to proper account

- terragrunt/org_account/iam_identity_center/platform_forms_assignments.tf
- terragrunt/org_account/iam_identity_center/platform_forms_groups.tf
Add two new groups that allow members to have read-only billing access to the Forms accounts.
> feat: add Forms Staging/Prod billing read only groups

- catalog-info.yaml
Updating the type of component this repo is representing
> fix: update type of component

- .devcontainer/devcontainer.json
- terragrunt/org_account/spend_notifier/lambdas/spend_notifier/spend_notifier.js
Small PR to add nodejs to the dev container since we are using it for the spend notifier lambda function.
> Adding node to the dev container

- terragrunt/org_account/iam_identity_center/digital_transformation_office_assignments.tf
- terragrunt/org_account/iam_identity_center/digital_transformation_office_groups.tf
- terragrunt/org_account/iam_identity_center/locals.tf
Adding DTO to the list of AWS SSO groups.
> Adding DTO to the AWS SSO groups

- terragrunt/org_account/cost_usage_report/iam.tf
- terragrunt/org_account/cost_usage_report/lambdas/billing_extract_tags/main.py
Update billing extract tags to allow it to write to write to the correct prefix in the data lake bucket.
- https://github.com/cds-snc/platform-core-services/issues/610
> fix: billing extract tags IAM role and S3 prefix

- terragrunt/org_account/iam_identity_center/locals.tf
- terragrunt/org_account/iam_identity_center/platform_superset_assignments.tf
- terragrunt/org_account/iam_identity_center/platform_superset_groups.tf
Add SSO groups for the Superset Staging account.
- https://github.com/cds-snc/site-reliability-engineering/issues/1352
- https://github.com/cds-snc/platform-core-services/issues/617
> feat: add Superset Staging SSO groups

- terragrunt/org_account/iam_identity_center/security_threat_modelling_groups.tf
Adding the security groups for the tread modelling tool.
> Adding security groups for thread modelling tool

- terragrunt/org_account/iam_identity_center/gc_signin_assignments.tf
- terragrunt/org_account/iam_identity_center/gc_signin_groups.tf
- terragrunt/org_account/iam_identity_center/locals.tf
Creating groups/permissions for GC Signin accounts.
> GC Sign in permissions

- terragrunt/org_account/iam_identity_center/digital_transformation_office_assignments.tf
- terragrunt/org_account/iam_identity_center/digital_transformation_office_groups.tf
- terragrunt/org_account/iam_identity_center/locals.tf
> Adding staging groups to AWS identity Centre

- terragrunt/org_account/iam_identity_center/digital_transformation_office_assignments.tf
- terragrunt/org_account/iam_identity_center/digital_transformation_office_groups.tf
- terragrunt/org_account/iam_identity_center/locals.tf
Adding the CRA dashboard groups and the appropriate permissions. Right now, only Hamza is a member.
> Adding CRA dashboard groups

- terragrunt/org_account/organization/organizations.tf
> revert: test policy
