cds-snc/cds-aws-lz

- .github/workflows/tf-apply.yml
- .github/workflows/tf-plan.yml
- terragrunt/org_account/main/oidc_role.tf
Adding a role that we can use to run plan on the AFT Module.
Also migrate to the new Terraform Tools setup action
> feat: add a new admin plan role

- terragrunt/org_account/main/main.tf
This is a required action so that Account Factory for Terraform has the
ability to trigger Account Factory in the root account.
https://learn.hashicorp.com/tutorials/terraform/aws-control-tower-aft#grant-aft-access-to-service-catalog-portfolio
Related to https://github.com/cds-snc/site-reliability-engineering/issues/393
> feat: attach the AFTExecution role to AF

- .github/workflows/tf-apply.yml
- .github/workflows/tf-plan.yml
- terragrunt/aft/main/slack_notify.tf
This should notify in the landing zone slack channel on messages sent to
aft-failure-notifications and aft-notifications.
This will close #16
> feat: notify in slack on AFT notifications

- .github/workflows/tf-apply.yml
- .github/workflows/tf-plan.yml
- terragrunt/audit/main/main.tf
- terragrunt/log_archive/main/.terraform.lock.hcl
- terragrunt/log_archive/main/main.tf
- terragrunt/log_archive/main/terragrunt.hcl
- terragrunt/log_archive/terragrunt.hcl
Removes the Sentinel Connectors OIDC for the audit account as we don't
need them.
Adds them instead to the log archive which is where the GD findings go.
Modifies the Workflows for terraform plan and action so that we aren't just copy and pasting stuff all over the place. 
**Please Note:** The OIDC Roles have been applied locally and so the changes will not show up in this PR.
> feat: add OIDC to Log Archive Account

- .github/workflows/tf-apply.yml
We have the Slack Webhook env variable in the plan action but forgot to
add it in the apply action
> fix: add environment variables to apply

- .github/workflows/tf-plan-aft.yml
- .github/workflows/tf-plan.yml
The AFT plan was running all the time and causing lock issues because it
ran on every commit.
The AFT plan will now only run if the workflow files have changed or the
code in the folder has changed.
> fix: Split out AFT plan from reg workflow

- terragrunt/org_account/main/main.tf
Added an aws_organizations_organization resource to manage what services
are available in the org.
This was imported locally, the only services that weren't already
enabled were guardduty and security hub
> feat: manage organization settings through TF

- .github/workflows/tf-apply.yml
Fail fast was causing issues as applys would fail and then it would cause locks on all the other states. 
State buckets are in a bad state so this may fail but this is the first step to trying to fix this thing.
> fix: remove fail_fast on apply

- terragrunt/log_archive/main/guardduty.tf
- Adds resources for existing detectors that were created when GD was enabled these resources were manually imported.
- Adds configuration for us-east-1 and us-west-2
- Removes master account as it has to have a different flow for invites.
Related to #34
> feat: configure in us regions

- terragrunt/log_archive/main/guardduty.tf
- terragrunt/org_account/main/guardduty.tf
- also configures the detectors for us_east_1 and us_west_2
- all of the changes in the log_archive account were automatically
created
- changes to resources in the org level account  are expected since all
I did was create the resources and import them.
> feat: enable guardduty in org account and invite

- terragrunt/log_archive/main/guardduty.tf
Invite all the accounts into the other enabled guardduty regions
I'm not 100% sure this is required, but it seems like it is, so lets do it anyways..
> feat: invite in other regions

- terragrunt/log_archive/main/guardduty.tf
failed on merge to main because I used the wrong detector
> fix: change detector in us_west_2 invites

- terragrunt/org_account/aft/main.tf
Now that we have enterprise support enabled it should be fine to toggle this to true.
> feat: toggle enterprise support

- terragrunt/audit/main/main.tf
Attaches the plan policies to the right role. 
Please note this needed to be applied locally in order to work.
> fix: attach policy to the correct role

- terragrunt/aft/main/assume_roles.tf
- terragrunt/audit/main/assume_roles.tf
- terragrunt/audit/main/main.tf
- terragrunt/log_archive/main/assume_roles.tf
- copies the pattern from the audit account and adds roles for the
AFT-Maintenance Account and the Log_Archive account
This is PR 1 of 2, the next one will be adding roles to the org account that allows it to assume into these roles
> feat: add roles to assume into in child accounts

- terragrunt/org_account/main/assume_roles.tf
Allow assuming into roles in the following accounts:
- Log Archive
- AFT Management
Audit was already done, and the other accounts in this org should not
need to be assumed into using the tf accounts.
> feat: allow assuming into roles in accounts

- terragrunt/org_account/main/securityhub.tf
- removes the AWS Best Practice subscription as that's apparently
enabled by default
- invites and accepts invites in all centrally managed accounts
Related to https://github.com/cds-snc/site-reliability-engineering/issues/471
> feat: invite existing centrally controlled systems

- terragrunt/org_account/main/securityhub.tf
last merge failed I'm assuming it's because SH needs to be enabled first
and that this is a different pattern from Guardduty that gets enabled
when you invite.
> fix: enable sh first before inviting

- terragrunt/org_account/main/securityhub.tf
The last PR failed because it looks like just enabling security hub is enough to add it to the delegated admin account...
> fix: remove unneeded invites

- terragrunt/org_account/main/securityhub.tf
I think I didn't have it working properly before and that inviting the
log archive which is the delegated admin account was causing the issues
not inviting the accounts.
This should hopefully work, but maybe not...
> feat: invite centrally managed accounts

- terragrunt/modules/assume_role/main.tf
- terragrunt/modules/existing_security_hub_member/input.tf
- terragrunt/modules/existing_security_hub_member/main.tf
- terragrunt/modules/existing_security_hub_member/providers.tf
- terragrunt/org_account/main/securityhub.tf
- refactored out adding existing security hub members through a module
- ignored changes to the email due to a known bug (see comment)
This also adds my personal IAM User as a trusted account to assume the assume_plan and assume_apply roles, this is required for refactoring and will be removed when that work is done.
**Please Note:** The refactoring work was done locally, I'm not quite ready to try out the move commands.
> refactor: security hub into a module

- terragrunt/org_account/main/guardduty.tf
Enable publishing guardduty findings in us_east_1 and us_west_2
> feat: publish findings in all regions

- .github/workflows/tf-apply.yml
- .github/workflows/tf-plan.yml
- terragrunt/org_account/main/input.tf
- terragrunt/org_account/main/sentinel_forwarders.tf
This uses the terraform module that is already in use by the ALZ org
account
This closes: https://github.com/cds-snc/site-reliability-engineering/issues/470
> feat: enable guardduty sentinel forwarding

- terragrunt/org_account/main/sentinel_forwarders.tf
Move the guardduty_forwarder module over to the log_archive account in ca-central-1 instaed of running it in the org_account which didn't work anyways.
This fixes bug #67 
**CHANGES WERE APPLIED LOCALLY**
> fix: move module to log_archive account

- terragrunt/org_account/main/sentinel_forwarders.tf
Closes https://github.com/cds-snc/site-reliability-engineering/issues/495 by adding a sentinel forwarder that attaches to the the cloud trail log bucket. TBD is if the KMS key that encrypts the logs needs to have the lambda principle added.
> feat: adds cloudtrail forwarder

- terragrunt/org_account/main/eventbridge.tf
- terragrunt/org_account/main/sentinel_forwarders.tf
Since we can just send from the log_archive account there is no need to
forward the events to another eventbridge like we did in the existing
Landing Zone Instance.
Closes https://github.com/cds-snc/site-reliability-engineering/issues/491
> feat: send security hub events to sentinel

- terragrunt/log_archive/main/main.tf
These creds aren't being used in any repo so are safe to remove.
> refactor: remove unsued sentinel credentials

- terragrunt/org_account/aft/main.tf
Changlog: 
https://github.com/aws-ia/terraform-aws-control_tower_account_factory/compare/1.4.2...1.6.2
Closes #77 as it's no longer needed
> feat: upgrade AFT to 1.6.2

- bin/migrate/create_awsctexec_role.sh
- bin/migrate/invoke_account.sh
- bin/migrate/remove_aft_created_resources.sh
Adds the following scripts that are used during account migration.
- bin/migrate/create_awsctexec_role.sh
Creates the `AWSControlTowerExecution` role that's required by control
tower for creating resources in the account
- bin/migrate/remove_aft_created_resources.sh
Deletes resources that are created by AFT, this should fail for some
lines of these script as some resources are only used by some environments
- bin/migrate/invoke_account.sh
Invokes the AFT codepipeline for a specific account
> feat: adds migration scripts

- bin/create_ops_users.sh
Related to https://github.com/cds-snc/site-reliability-engineering/issues/572 
Adds AdministratorAccess policy to admins group upon account creation
> feat: Add AdminAccess policy to admins group

- bin/one-offs/add_admin_policy.sh
Fixes some issue because the script was using roles from the previous org
> fix: make one off work for new org

- .github/workflows/tf-apply.yml
The previous PR ran a tf plan in the right module but tried to apply the main module again. 
It failed due to a statelock this one should work.
> fix: apply right module

- terragrunt/org_account/spend_notifier/lambda.tf
- terragrunt/org_account/spend_notifier/lambdas/spend_notifier/spend_notifier.js
- Increase timeout to 30 seconds
- Allow Eventbridge rules to invoke lambda
- Remove 0 concurrent runs
- Change key of Business Unit tag to match new values
This will still fail in the SRE bot message but I think the fix is there not here.
> fix: issues with spend_notifier lambda

- terragrunt/org_account/spend_notifier/iam.tf
- terragrunt/org_account/spend_notifier/lambda.tf
Attach the policy for lambda insights.
Create a log group so we can figure out why it failed to execute from
eventbridge.
> fix: add log group and lambda insights

- .github/workflows/tf-apply.yml
- .github/workflows/tf-plan.yml
- terragrunt/org_account/spend_notifier/eventbridge.tf
- terragrunt/org_account/spend_notifier/inputs.tf
We were using the same hook for weekly and daily so it was printing the
weekly spend to the wrong place, this should fix it.
The weekly hook has been added to gh secrets
> fix: add weekly spend notifier hook

- terragrunt/org_account/main/locals.tf
- terragrunt/org_account/main/oidc_role.tf
Add an OIDC role that will be used by the `site-reliability-engineering` repo to manage SSO permission assignments.
This will be used by the [on-call rotate script workflow](https://github.com/cds-snc/site-reliability-engineering/blob/main/.github/workflows/on_call_rotate_notify.yml).
- cds-snc/site-reliability-engineering#594
> feat: SRE OIDC role to manage permissions

- bin/create_ops_users.sh
Update the create Ops user script to set a default region.  Not having
this set caused an error when I was using the script with exported
AWS credentials rather than a configured AWS cli profile.
> fix: set default region in the create ops script

- terragrunt/org_account/spend_notifier/lambdas/spend_notifier/spend_notifier.js
Because we are too afraid to enroll the old credit card account we are
left with some untagged accounts. This fix will handle it till we are
comfortable enrolling it.
This will categorize untagged accounts as "Not tagged" in the spend notifier lambda.
> fix: handle untagged accounts.

- .github/workflows/tf-apply.yml
- .github/workflows/tf-plan.yml
- terragrunt/log_archive/legacy_archives/main.tf
- terragrunt/org_account/sre_bot/iam.tf
- terragrunt/org_account/sre_bot/locals.tf
- terragrunt/org_account/sre_bot/terragrunt.hcl
This PR adds a role and policy for the SRE Bot in it's account to access read resources inside the org account for trusted advisor and the org list.
> feat: add role for SRE bot

- .github/workflows/tf-apply.yml
- .github/workflows/tf-plan.yml
- terragrunt/org_account/sre_bot/iam.tf
- terragrunt/org_account/sre_bot/inputs.tf
This PR adds the Admin SSO role ARN as a secret to the principles that can assume roles for SRE-Bot
> fix: add admin_sso_role_arn as a secret

- .github/workflows/tf-apply.yml
- .github/workflows/tf-plan.yml
- terragrunt/log_archive/sre_bot/iam.tf
- terragrunt/log_archive/sre_bot/inputs.tf
- terragrunt/log_archive/sre_bot/locals.tf
- terragrunt/log_archive/sre_bot/terragrunt.hcl
Removes the Trusted Advisor from the org IAM rule. Adds an IAM roles to the logging account for SecurityHub and GuardDuty.
> feat: add roles for log archive

- .github/workflows/tf-apply.yml
- .github/workflows/tf-plan.yml
- terragrunt/audit/sre_bot/iam.tf
- terragrunt/audit/sre_bot/inputs.tf
- terragrunt/audit/sre_bot/locals.tf
- terragrunt/audit/sre_bot/terragrunt.hcl
This PR adds a role for the audit account that let the SRE bot look up AWS Config data. It also scopes down the SRE bot role to the Log account to the actual resources the SRE bot needs.
> feat: add audit account role for SRE bot

- terragrunt/org_account/main/sentinel_cloudtrail.tf
This removes the KMS key from the SQS queue to enable the notification process.
> fix: remove kms key

- terragrunt/org_account/main/scp.tf
Closes https://github.com/cds-snc/cds-aws-lz/issues/38. This PR adds additional SCPs based on the recommendations from here https://summitroute.com/blog/2020/03/25/aws_scp_best_practices/ and some CDS config items.
They include:
- Blocking all IAM user creation other than `ops1` and `ops2`.
- Blocking the deletion of `ops1` and `osp2` users
- Blocking an account from leaving the org and thus dropping SCPs
- Blocking the deletion of access analyzer
- Turning of EBS Encryption by default
> feat: additional SCPs

- .github/workflows/tf-apply.yml
- .github/workflows/tf-plan.yml
- terragrunt/org_account/.terraform.lock.hcl
- terragrunt/org_account/sentinel_oidc/.terraform.lock.hcl
- terragrunt/org_account/sentinel_oidc/iam.tf
- terragrunt/org_account/sentinel_oidc/idp.tf
- terragrunt/org_account/sentinel_oidc/terragrunt.hcl
This PR saves these resources created by clickOps:
- an OICD identity provider 
- an IAM role
- a role policy attachment 
Resources have been imported already.  This resolves cds-snc/create_watchlist#8
> save click ops to terraform for Sentinel OIDC

- terragrunt/aft/notifications/aft-notifications.tf
This SNS topic is way too noisy we should only really subscribe to the negative one, if we want to listen to positive we should change how we do it.
> fix: remove positive sns topic

- terragrunt/org_account/roles/.terraform.lock.hcl
- terragrunt/org_account/roles/cartography.tf
This role is going to be used by the cartography state machine so that
it can get the list of account ids.
> feat: add a role that can list account ids

- terragrunt/modules/assume_role/inputs.tf
- terragrunt/modules/assume_role/main.tf
Previously I had hardcoded my personal IAM User into the module in order
to allow me to plan/apply from my local machine.
This change will allow us to pass in an arbitrary number of roles, it
also allows us to easily add or remove roles without having to mess with
the module, so we can open PR's only as long as we require the ability
to do local work.
I'm also removing my personal IAM User as I don't need to assume any roles at the moment
> feat: allow roles to assume for local apply/plan

- terragrunt/log_archive/sre_bot/sre_vulnerability_report.tf
Update the GuardDuty IAM permissions to allow for retrieval of GuardDuty findings.
- cds-snc/site-reliability-engineering#738
> fix: add vulnerability report IAM permissions

- terragrunt/org_account/roles/cartography.tf
Add the role that cartography will use to get all account ids.
Work was click-opsed and imported/applied locally.
> feat: imported Clickops changes

- bin/create_ops_users.sh
Updating the script to:
- Format LastPass notes based on current standard
- Get 64 character password from AWS Secrets Manager
> fix: format ops passwords + length

- bin/update_ops_users_passwords.sh
Updating password length when rotating OPS passwords. Related to #173
> fix: update password length

- terragrunt/org_account/organization/guardrails.tf
- terragrunt/org_account/organization/organizations.tf
This enables trusted access in the organization which will allow org admins to modify account information from the organization account. 
https://docs.aws.amazon.com/accounts/latest/reference/manage-acct-update-contact-primary.html
This will allow me to change the phone number associated with any account thus allowing me to fix this issue: https://github.com/cds-snc/site-reliability-engineering/issues/798 without having to bug internal ops folks to sit in a meeting with me while I change MFA on the account.
> feat: enable trusted access

- terragrunt/org_account/organization/scp.tf
This prevents the SCP user from performing any action except for the few
identified here: https://docs.aws.amazon.com/accounts/latest/reference/root-user-tasks.html
Well some of them, obviously there are some tasks we will never do like
sell on the market place or sign up for AWS GovCloud (US)
Some of these taks were grabbed from the ASEA Root SCP: https://github.com/aws-samples/aws-secure-environment-accelerator/blob/main/reference-artifacts/SCPs/ASEA-Guardrails-Sensitive.json#L21-L42
closes https://github.com/cds-snc/security-risk-register/issues/15
closes https://github.com/cds-snc/site-reliability-engineering/issues/755
> feat: add an SCP on the root user.

- terragrunt/aft/notifications/aft-notifications.tf
Because of an overly noisy sns topic we are getting alerts on expected behaviours not failures, so I'm turning this off until it is hopefully addressed. 
Closes #182
> feat: stop alerting on aft-failure-notifications

- terragrunt/org_account/organization/organizations.tf
This is required to re-register an OU in Control Tower.
We recieved the following error when trying to register.
>Account enrollment failed.
AWS Control Tower could not enroll your account for the following reason: AWS Control Tower operation failed because trusted access for AWS CloudFormation was disabled. Please enable trusted access using the AWS CloudFormation console.
Docs for enabling this: https://docs.aws.amazon.com/organizations/latest/userguide/services-that-can-integrate-cloudformation.html
Related to #181
> feat: enable trusted access to CF Stacksets

- terragrunt/org_account/aft/main.tf
Account factory for terraform 1.9.0 fixes the issue with too many errors
going to the aft-failure-notification sns topic.
And just upgraded to the latest version of 1.3.9
Closes #186
> feat: upgrade aft to 1.9.0 and TF to latest patch

- terragrunt/aft/notifications/aft-notifications.tf
Now that we've updated AFT to 1.9.0
> feat: re-enable aft-failure-notification slack integration

- terragrunt/org_account/organization/organizations.tf
- terragrunt/org_account/organization/scp.tf
Setting up temporary SCPs to grant specific and limited permissions to run Cartography for asset inventory.
It should:
- Replicate the Control Tower's default [Deny Region SCP](https://docs.aws.amazon.com/controltower/latest/userguide/data-residency-controls.html#primary-region-deny-policy) and include the `secopsAssetInventorySecurityAuditRole` role
- Prevent the creation of access keys for the `secopsAssetInventorySecurityAuditRole` role
- Prevent all modifications to the `secopsAssetInventorySecurityAuditRole` role except by `AWSAFTExecution` role
Fixes https://github.com/cds-snc/site-reliability-engineering/issues/830
> feat: add temp SCP for Cartography execution

- terragrunt/org_account/aft/main.tf
Upgrades AFT to the latest version 1.10.3
Docs for upgrade: 
https://github.com/aws-ia/terraform-aws-control_tower_account_factory/compare/1.9.1...1.10.3
This fix should address some compliance issues with the s3 buckets this thing creates 
>Amazon S3 now automatically enables S3 Block Public Access and disables the use of access control lists for all newly created buckets. Due to this change, the ACLs applied to AFT buckets have been removed.
> feat: upgrade aft to 1.10.3

- terragrunt/org_account/organization/scp.tf
Prevent the deletion of specific Route53 hosted zones.
> feat: add SCP statement to deny hosted zone delete

- terragrunt/aft/main/assume_roles.tf
- terragrunt/aft/main/main.tf
- terragrunt/aft/main/slack_notify.tf
- terragrunt/aft/notifications/aft-notifications.tf
- terragrunt/audit/main/assume_roles.tf
- terragrunt/log_archive/legacy_archives/main.tf
- terragrunt/log_archive/main/assume_roles.tf
- terragrunt/log_archive/sre_bot/OIDC.tf
- terragrunt/org_account/main/alarms.tf
- terragrunt/org_account/main/guardduty.tf
- terragrunt/org_account/main/main.tf
- terragrunt/org_account/main/oidc_role.tf
- terragrunt/org_account/main/sentinel_forwarders.tf
- terragrunt/org_account/roles/OIDC.tf
Changing the terraform source module reference to use the format as documented in the terraform documentation - https://developer.hashicorp.com/terraform/language/modules/sources#modules-in-package-sub-directories.
I am sorry, but I did not update the modules to use the latest version since I did not want to break anything such mission critical. If you think it is safe for me to do so, I am happy to update to the latest version.
> Changing references of terraform modules

- terragrunt/org_account/spend_notifier/lambdas/spend_notifier/spend_notifier.js
Modified the spend notifier function to detect increases in AWS cost increase of 35% from previous days. The new code loops through the costs from yesterday and the day before and calculates the percentage difference between those 2 days. If yesterday saw a 35% plus increase from the day before yesterday, then the message with the accounts affected is added to the alert notification sent in Slack.  This is what the message will look like:
> Alert on 35% increases in daily AWS account cost

- terragrunt/org_account/spend_notifier/lambdas/spend_notifier/spend_notifier.js
The following changes were made to the spend notifier lambda function:
- If the account is not a scratch account, only then the daily account increases will be taken into consideration. 
- If a scratch account exceeds $500 in a day and it did not do so the previous day, then it will get reported.
The new message will look something like this:
> Changing notification based on scratch accounts

- terragrunt/org_account/spend_notifier/lambdas/spend_notifier/spend_notifier.js
Changing the is scratch account checking to be more efficient and properly done since we already store whether the account is scratch or not.
> Changing scratch account checking

- terragrunt/log_archive/sre_bot/OIDC.tf
- terragrunt/log_archive/sre_bot/locals.tf
- terragrunt/log_archive/sre_bot/sre_sechub_automation_rules.tf
Add an OIDC rule that can be used by the SRE repo by the [`tools/aws-security-automation-rules`](https://github.com/cds-snc/site-reliability-engineering/blob/main/tools/aws-security-hub-automation-rules/README.md) script to manage Security Hub automation rules.
- https://github.com/cds-snc/site-reliability-engineering/pull/1020
- https://github.com/cds-snc/platform-core-services/issues/471
> feat: add SRE Security Hub automation rule role

- terragrunt/modules/existing_security_hub_member/main.tf
Update the member account Security Hub resource as the settings are inherited from the Security Hub administrator account.
- https://github.com/cds-snc/platform-core-services/issues/471
> fix: member accounts inherit Security Hub settings

- terragrunt/org_account/spend_notifier/iam.tf
The cloudspend lambda function was not referencing the right log group and as a result, we were not getting logs.
> Changing the log group so that we can receive logging events

- terragrunt/org_account/organization/guardrails.tf
- terragrunt/org_account/organization/organizations.tf
Destroy the Sandbox OU before creating a new one.
> fix/partial: destroy Sandbox OU

- terragrunt/org_account/organization/guardrails.tf
- terragrunt/org_account/organization/organizations.tf
> fix: create new sandbox OU

- terragrunt/org_account/spend_notifier/lambdas/spend_notifier/spend_notifier.js
Changes were made so that we do not alert if the dollar increase is less than $10 between yesterday and the day before.
> Do not alert if the dollar increase is less than $10. 

- terragrunt/org_account/spend_notifier/lambdas/spend_notifier/spend_notifier.js
Fixes an error that always exists on the second of the month where the lambda function fails due to the following error message " "errorType": "ValidationException","errorMessage": "Start date (and hour) should be before end date (and hour)" from the Cost explorer API.
> Fixing error that exists on the second of the month

- terragrunt/org_account/billing_extract_tags/lambdas/billing_extract_tags/main.py
- terragrunt/org_account/billing_extract_tags/lambdas/billing_extract_tags/test_main.py
- terragrunt/org_account/billing_extract_tags/s3.tf
Update the Lambda function to add newlines between each billing tag export line.  These are required by AWS Glue for parsing the JSON data.
Remove the `import` blocks as the resources have new been brought into the TF state.
> fix: add newlines back to billing tag JSON export

- terragrunt/org_account/organization/scp.tf
SCP that we can attach to a quarantine or dumpster fire OU that would allow us to deny all actions on compromised accounts.
> SCP to deny everything in case of an emergency

- terragrunt/org_account/roles/OIDC.tf
- terragrunt/org_account/roles/inputs.tf
- terragrunt/org_account/roles/locals.tf
- terragrunt/org_account/roles/sre_identity_audit.tf
Setting up an OIDC role for the SRE Audit tool to be assumed by the GH action
> feat: setup OIDC role for the SRE Audit tool

- terragrunt/org_account/organization/scp.tf
Excluding ops1 and ops2 from the deny all policy.
> Excluding ops1 and ops2 from deny all policy

- .github/workflows/tf-apply.yml
- .github/workflows/tf-plan.yml
- terragrunt/org_account/iam_identity_center/data.tf
- terragrunt/org_account/iam_identity_center/locals.tf
- terragrunt/org_account/iam_identity_center/platform_articles.tf
- terragrunt/org_account/iam_identity_center/terragrunt.hcl
Add a module that can manage the IAM Identity Center groups, permission sets and account assignments.
This includes the GitHub workflow changes and the GC Articles target state group and account assignments.
> feat: add IAM Identity Center module

- terragrunt/org_account/main/README.md
- terragrunt/org_account/main/sentinel_forwarders.tf
Update to the Terraform Sentinel Forwarder module that does not store its authentication credentials as Lambda env vars.
- https://github.com/cds-snc/platform-core-services/issues/557
- https://github.com/cds-snc/site-reliability-engineering/issues/1215
> chore: update to latest Sentinel Forwarder module

- terragrunt/org_account/roles/sre_bot.tf
Adding permissions for the SRE bot to handle users in Identity center (SSO Identity Center only, not root or IAM users)
> feat: add permissions for bot to manage SSO users

- terragrunt/org_account/roles/sre_bot.tf
Adding permissions to create and delete group memberships to the SRE bot role.
Required in order to add/remove users from SSO groups via the bot's Integration
> feat: update permissions to include group memberships managemtn

- terragrunt/aft/notifications/cloudwatch.tf
Add a CloudWatch metric and alarm to alert when an AFT Terraform pipeline execution fails.
> feat: add AFT pipeline CloudWatch metric alarm

- terragrunt/aft/notifications/cloudwatch.tf
- terragrunt/aft/notifications/input.tf
- terragrunt/aft/notifications/sns.tf
Add an SNS topic, subscription and KMS key for the AFT CloudWatch alarms. 
This is required as the `aft-failure-notifications` SNS topic's KMS key does not allow CloudWatch to publish messages.
> fix: add SNS topic for AFT CloudWatch alarms

- terragrunt/org_account/iam_identity_center/platform_notify_assignments.tf
- terragrunt/org_account/iam_identity_center/platform_notify_permissions.tf
Update the permission sets to use inline IAM policies.  Customer managed policies would need to exist in each account that the permission set is applied to which would be challenging to manage.
> fix: switch to inline IAM policies for permission sets

- terragrunt/org_account/iam_identity_center/platform_notify_permissions.tf
Update the ECS Blazer inline policy to use the correct `ArnLike` key.
> fix: ArnLike IAM condition on Blazer policy

- terragrunt/org_account/iam_identity_center/platform_articles_groups.tf
- terragrunt/org_account/iam_identity_center/platform_notify_groups.tf
- terragrunt/org_account/iam_identity_center/platform_notify_permissions.tf
Update the IAM Identity Center group and permissoin names to put the service name before the role:
```
Product-Env(-Service)(-Resource)-Role
```
This will make it easier for people to identify the service as they grant and revoke access.
> fix: rename Identity Center groups and permissions

- terragrunt/org_account/iam_identity_center/platform_articles_assignments.tf
Update the Articles IAM Identity Center permission assignments so that they are explicitly created per account rather than relying on a dynamic account ID.
> fix: switch to per account permission assignments

- terragrunt/org_account/iam_identity_center/platform_notify_assignments.tf
- terragrunt/org_account/iam_identity_center/platform_notify_permissions.tf
Update to use the existing QuickSight permission set as the SSO role this has created is part of the existing QuickSight usernames.
This will allow us to keep existing users and their analysis/dashboard access.
> fix: use existing QuickSight permission set

- terragrunt/org_account/iam_identity_center/locals.tf
- terragrunt/org_account/iam_identity_center/platform_articles_assignments.tf
- terragrunt/org_account/iam_identity_center/platform_forms_assignments.tf
- terragrunt/org_account/iam_identity_center/platform_forms_groups.tf
- terragrunt/org_account/iam_identity_center/platform_notify_assignments.tf
Add the Forms groups and their account permission set assignments.
Refactor the Notify and Articles permission assignment Terraform state references to match the Forms' assignments.  This gives more flexibility in assigning multiple permission sets to a group.
> feat: Forms groups and account assignments

- terragrunt/org_account/iam_identity_center/platform_forms_assignments.tf
- terragrunt/org_account/iam_identity_center/platform_forms_groups.tf
- terragrunt/org_account/iam_identity_center/platform_forms_permissions.tf
Add new Staging/Production groups that allow users access to run RDS queries using the Query Editor.
- https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/query-editor.html#query-editor.access
> feat: Forms RDS query editor access group

- terragrunt/org_account/iam_identity_center/platform_forms_permissions.tf
Update the RDS query access permission to allow it to describe RDS resources.
- #267
> fix: add missing RDS describe permission

- .github/workflows/tf-drift-check.yml
- .github/workflows/tf-plan.yml
Add a GitHub workflow that checks for drift between the Terraform and AWS cloud infrastructure.
After testing, this will be set to run on a schedule and post to a Slack channel when drift is detected.
- https://github.com/cds-snc/platform-core-services/issues/571
> feat: add Terraform drift check workflow

- .github/workflows/export_github_data.yml
Add common workflow to export GitHub metadata to Sentinel.
> chore: add GitHub metadata exporter workflow

- .github/workflows/tf-drift-check.yml
- .github/workflows/workflow-failure.yml
Run a nightly Terraform drift check to make sure the Landing Zone Terraform and resources are in sync.
Add a new workflow that posts to `#internal-sre-alerts` when one of its named workflows fails.
> feat: add scheduled Terraform drift check

- .github/workflows/tf-drift-check.yml
Update the Terraform drift check to remove the `roles` module. This is being done because this module is frequently changed to allow for local dev and testing of SRE bot features.
> fix: remove role module from drift check

- terragrunt/org_account/spend_notifier/lambdas/spend_notifier/spend_notifier.js
Adding a user agent to the headers, otherwise we get a 403 Forbidden due to a change in https module and the lambda function can't post to the SRE bot. 
This was a total pain to debug!
> Adding user agent otherwise we get a 403 Forbidden error

- terragrunt/org_account/iam_identity_center/common_permissions.tf
Update the `SupportCenter-Admin` permission set to allow users to manage the Pinpoint SMS opt-out lists.
This is required as Notify is moving to using Pinpoint to manage SMS.
> feat: allow update of Pinpoint SMS opt-out lists

- terragrunt/org_account/organization/organizations.tf
- terragrunt/org_account/organization/scp.tf
Attempt to further restrict possible locking out of accounts via AWS Nuke
> feat: setup narrower guardrails against aws Nuke

- terragrunt/org_account/iam_identity_center/platform_forms_assignments.tf
- terragrunt/org_account/iam_identity_center/platform_forms_groups.tf
- terragrunt/org_account/iam_identity_center/platform_forms_permissions.tf
Add a new permission set that allows uses to run Athena queries using the Forms service logs as well as the RDS and DynamoDB lambda connectors.
- https://github.com/cds-snc/platform-core-services/issues/587
- cds-snc/platform-forms-client#3586
> feat: Forms Athena query access permission set

- terragrunt/org_account/iam_identity_center/platform_forms_permissions.tf
Update the Forms Athena query access permission set to include the ability to read from the data connector spill bucket.
- https://github.com/cds-snc/platform-core-services/issues/587
- cds-snc/platform-forms-client#3586
> fix: add missing spill bucket permissions

- terragrunt/org_account/iam_identity_center/common_permissions.tf
Update the `SupportCenter-Admin` permission set so that it is able to validate phone numbers in Pinpoint.
- https://github.com/cds-snc/site-reliability-engineering/issues/1314
> feat: allow support center admin to validate phone numbers

- terragrunt/org_account/iam_identity_center/common_permissions.tf
Update the permissions to allow the opt-out phone number lists to load without errors in the AWS console.
- Closes https://github.com/cds-snc/site-reliability-engineering/issues/1324
> fix: add missing SupportCenter-Admin permissions

- terragrunt/org_account/iam_identity_center/locals.tf
- terragrunt/org_account/iam_identity_center/platform_data_lake_assignments.tf
- terragrunt/org_account/iam_identity_center/platform_data_lake_groups.tf
Add Admin, ReadOnly and Billing-ReadOnly AWS SSO groups.
- https://github.com/cds-snc/site-reliability-engineering/issues/1339
- https://github.com/cds-snc/platform-core-services/issues/608
> feat: add AWS SSO groups for DataLake-Production

- .github/workflows/tf-apply.yml
- .github/workflows/tf-drift-check.yml
- .github/workflows/tf-plan.yml
- terragrunt/org_account/main/README.md
- terragrunt/org_account/main/input.tf
- terragrunt/org_account/main/sentinel_cloudtrail.tf
Fixes #324 
Allows us to pass in multiple log analytics workspace ids to the Azure sentinel role. This is a temporary issue that we need to deal with since we are using 2 log workspaces to recreate the infrastructure in the new landing zone for the Sentinel connectors . Once we have recreated everything, we can move only to one workspace id. 
I also removed the delay for the SQS queue since it was not necessary and updated the polling delay as well so in theory that should speed up the ingestion delay in Sentinel.
> Adding ability to send multiple workspaces to the Azure sentinel role

- terragrunt/org_account/main/sentinel_cloudtrail.tf
Remove the receive_wait_time_seconds attribute for the sqs queue to wait for the message to return before arriving. This might speed up the processing of Sentinel messages.
> Reducing Receive wait time for message to 0 to speed up ingestion

- terragrunt/org_account/main/sentinel_cloudtrail.tf
Reverts cds-snc/cds-aws-lz#326
Reverting because this actually made ingestion delay worse. I did not assume that we have as many empty messages and enable some long polling is to our advantage.
> Revert "Reducing Receive wait time for message to 0 to speed up ingestion"

- terragrunt/log_archive/sre_bot/OIDC.tf
- terragrunt/log_archive/sre_bot/locals.tf
- terragrunt/log_archive/sre_bot/security_oscal_report.tf
Adding role for security team to be able to run via a Github action a report to find Config and SecurityHub findings.
> Adding role for the security team to be able generate OSCAL reports

- terragrunt/log_archive/sre_bot/security_oscal_report.tf
The security team wants to be able to refresh findings, enable more standards and basically have full permissions to Security Hub. It has been approved by the higher ups.
> Change permissions of Oscal report role

- terragrunt/org_account/spend_notifier/lambdas/spend_notifier/spend_notifier.js
Adding the FY total spending to the alert so that we can track better and have more visibility into our AWS spending.
> Adding FY total spending to alert

- terragrunt/org_account/iam_identity_center/locals.tf
- terragrunt/org_account/iam_identity_center/platform_articles_assignments.tf
Remove the List Manager permissions from the GC Articles group.
- https://github.com/cds-snc/site-reliability-engineering/issues/1495
> chore: remove List Manager permissions

- terragrunt/org_account/main/alarms.tf
Encrypting the critical and warning SNS topic with a KMS key as is required by the 30 day guardrails.
> Encrypting SNS topics with KMS key as required for the 30 day guardrails. 

- terragrunt/org_account/iam_identity_center/gc_signin_assignments.tf
- terragrunt/org_account/iam_identity_center/gc_signin_groups.tf
- terragrunt/org_account/iam_identity_center/locals.tf
Adding GC Signin groups for access to the new GCSignin test account.
> Adding GC Signin test groups

- terragrunt/org_account/roles/sre_bot.tf
This pull request adds a new permission statement to the SRE bot IAM policy to enable management of AWS SSO account assignments.
**IAM Policy Updates:**
* Added a new statement to the `aws_iam_policy_document.sre_bot_policy` allowing the actions `sso:ListAccountAssignmentsForPrincipal` and `sso:CreateAccountAssignment` on all resources, enabling the SRE bot to manage SSO account assignments.
> feat: add account assignement permission for Bot

- terragrunt/aft/main/output.tf
- terragrunt/aft/notifications/aft-notifications.tf
- terragrunt/aft/notifications/cloudwatch.tf
- terragrunt/aft/notifications/input.tf
- terragrunt/aft/notifications/terragrunt.hcl
- terragrunt/aft/terragrunt.hcl
This pull request introduces new notification capabilities to the AFT (Account Factory for Terraform) system by adding Slack integration and automating notifications for new AWS account creation events. The changes primarily focus on expanding notification channels and improving event-driven automation.
**Notification enhancements:**
* Added a new SNS topic subscription for Slack notifications, enabling Lambda-based delivery of alerts to Slack (`aws_sns_topic_subscription.slack_notification` in `aft-notifications.tf`).
**Event-driven automation:**
* Created a CloudWatch Event Rule to detect new AWS account creation events by monitoring the `CreateManagedAccount` event from AWS Control Tower (`aws_cloudwatch_event_rule.new_account_created` in `cloudwatch.tf`).
* Added a CloudWatch Event …
> feat: add CloudWatch event rule and target for new account creation

- terragrunt/org_account/iam_identity_center/digital_transformation_office_assignments.tf
- terragrunt/org_account/iam_identity_center/digital_transformation_office_permissions.tf
Adding a custom permission set for the CRA ReadOnly group to get objects from their S3 bucket.
> feat: add custom GetObject permission for CRA ReadOnly role
